### PR TITLE
Add support for yaml config file

### PR DESCRIPTION
**Pull request by jsumners**
WIP

### CODE REVIEW

**Comment by jsumners** [comment]
@mcollina please approve the CI run. I need to see what happens on Windows.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jsumners** [comment]
Looks like #104 is needed regardless. I was hoping adding this feature would negate needing to do anything else special for Windows 😢.

**Comment by mcollina** [comment]
Should I land #104 then?

**Comment by jsumners** [comment]
Ping for workflow run @mcollina (thanks GitHub).

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jsumners** [comment]
image

**Comment by jsumners** [comment]
image

**Pull request merged**
