### PR TITLE
feat: add `--expose-gc` flag

### PR DESCRIPTION
**Pull request by anurag-roy**
Addresses #3

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add it to the docs?

**Comment by anurag-roy** [comment]
I was trying out a few different ways to achieve this.

Since [we are using run from node:test here](https://github.com/mcollina/borp/blob/main/lib/run.js#L127) and not spawning a new process, we have two options:

 ### 1. Enable gc dynamically (without passing flags to node)
 
 ```js
 import { setFlagsFromString } from 'node:v8';
import { runInNewContext } from 'node:vm';

if (args.values['expose-gc'] && typeof global.gc !== 'function') {
  setFlagsFromString('--expose-gc');
  global.gc = runInNewContext('gc');
}
 ```
 
 I tried this, but was unable to use gc inside my tests
 
 ### 2. Spawn a node child process where we pass the `--expose-gc` flag
 
 ```js
 if (args.values['expose-gc'] && typeof global.gc !== 'function') {
  try {
    await execa('node', ['--expose-gc', ...process.argv.slice(1)], {
      stdio: 'inherit',
      env: {
        ...process.env
      }
    })
    process.exit(0)
  } catch (error) {
    process.exit(1)
  }
}
```
This one does work, but I'm not sure if this is the best way. Any pointers? @mcollina

**Comment by mcollina** [comment]
I think you can set it to process.env.NODE_OPTIONS before calling `run`

**Comment by anurag-roy** [comment]
No that will not work, since it isn't a node option it's a v8 flag.
```bash
$ node --v8-options

--expose-gc (expose gc extension)
        type: bool  default: false
 ```
 
 And passing it as NODE_OPTIONS gives this error
 ```
 node: --expose-gc is not allowed in NODE_OPTIONS
```

**Comment by mcollina** [comment]
I recommend you to open an issue on nodejs to add the possibility to pass nodeOptions to `run`.

Until that happens, using execa is ok.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by anurag-roy** [comment]
Yes sure, let me check why they are failing on v21

**Comment by anurag-roy** [comment]
Hey @mcollina you might want to take a look at this, something very weird is happening.

All tests are failing on v21.5, but passing on v21.4. When we are running `node borp.js` through execa, it seems as if none of the tests inside that child process are running. This is the output from `execa`
```
TAP version 13
1..0
# tests 0
# suites 0
# pass 0
# fail 0
# cancelled 0
# skipped 0
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
# todo 0
# duration_ms 8.481937
```

Do you have any idea what might be the issue?

**Comment by mcollina** [comment]
Here is the fix: https://github.com/mcollina/borp/pull/5

**Comment by anurag-roy** [comment]
Awesome! All tests passing now!

**Pull request merged**
