### PR TITLE
feat: added --no-timeout option

### LINKED ISSUE #20: enhancement: disable timeout
Either a `--no-timeout` flag, or ideally something that detects if a debugger is attached and automatically disables the timeout. 

Current workaround:

```sh
borp -t 23948672
```

### PR DESCRIPTION
**Pull request by 10xLaCroixDrinker**
Closes #20

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
This is failing on Wndows

**Comment by 10xLaCroixDrinker** [comment]
> This is failing on Wndows

I think f99feb4 should resolve this

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
